export const Colors: {[key: string]: string} = {
  background: 'rgba(255, 255, 255, 1)',
  primaryText: 'rgba(71, 85, 105, 1)',
  secondaryText: 'rgba(100, 116, 139, 1)',
  gradient1: 'rgba(64, 123, 255, 1)',
  gradient2: 'rgba(92, 142, 255, 1)',
  buttonColor: 'rgba(235, 245, 255, 1)',
  inputFieldColor: 'rgba(216, 218, 221, 1)',
  placeholderColor: 'rgba(107, 114, 128, 1)',
  brown: 'rgba(68, 64, 60, 1)',
  inputTextColor: 'rgba(0, 0, 0, 0.8)',
  error: 'rgb(246, 98, 98)',
};

export const Icons: {[key: string]: any} = {
  customer: require('../assets/icons/customer.png'),
  owner: require('../assets/icons/owner.png'),
  edit: require('../assets/icons/Edit-Icon.png'),
  home: require('../assets/icons/homeActive.png'),
  msg: require('../assets/icons/msg.png'),
  job: require('../assets/icons/job.png'),
  settings: require('../assets/icons/setting.png'),
  profile: require('../assets/icons/profile-inactive.png'),
  msgActive: require('../assets/icons/msg-active.png'),
  jobActive: require('../assets/icons/job-active.png'),
  settingActive: require('../assets/icons/settingsActive.png'),
  profileActive: require('../assets/icons/profileActive2.png'),
  homeInactive: require('../assets/icons/home-inactive.png'),
  homeLogo: require('../assets/icons/homeLogo.png'),
  category: require('../assets/icons/category.png'),
  availability: require('../assets/icons/availability.png'),
  calendar: require('../assets/icons/calendar-2.png'),
  editProfile: require('../assets/icons/editProfile.png'),
  delete: require('../assets/icons/delete.png'),
  arrowRight: require('../assets/icons/arrow-right.png'),
  priceRange: require('../assets/icons/price-range.png'),
  verify: require('../assets/icons/verify.png'),
  bars: require('../assets/icons/bars.png'),
  location: require('../assets/icons/location-2.png'),
  policy: require('../assets/icons/policy.png'),
  faqs: require('../assets/icons/Faqs.png'),
  logOut: require('../assets/icons/log-out.png'),
  terms: require('../assets/icons/terms.png'),
  dashBoard: require('../assets/icons/dashboard.png'),
  gallery: require('../assets/icons/gallery.png'),
  all: require('../assets/icons/menu.png'),
  residential: require('../assets/icons/house.png'),
  pressure: require('../assets/icons/pressure-washer.png'),
  window: require('../assets/icons/window-cleaning.png'),
  chimney: require('../assets/icons/chimney.png'),
  car: require('../assets/icons/car.png'),
  carpet: require('../assets/icons/carpet-cleaner.png'),
  editIcon: require('../assets/icons/message-edit.png'),
  remove: require('../assets/icons/remove-user.png'),
  timeEdit: require('../assets/icons/time-edit.png'),
  empty: require('../assets/icons/empty.png'),
  others: require('../assets/icons/more.png'),
  lawn: require('../assets/icons/lawn.png'),
  priceRangeWhite: require('../assets/icons/card-white.png'),
  verifyWhite: require('../assets/icons/verify-white.png'),
  locationWhite: require('../assets/icons/location-white.png'),
  slider: require('../assets/icons/cd.png'),
  availablityEdit: require('../assets/icons/avail.png'),
};

export const IMAGES: {[key: string]: any} = {
  onBoarding1: require('../assets/images/onBoarding1.png'),
  onBoarding2: require('../assets/images/onBoarding2.png'),
  onBoarding3: require('../assets/images/onBoarding3.png'),
  logo: require('../assets/images/logo.png'),
  stars: require('../assets/images/stars.png'),
  star: require('../assets/images/star.png'),
  defaultPic: require('../assets/images/user.png'),
  chat: require('../assets/images/chat.jpeg'),
};

export const Fonts: {[key: string]: string} = {
  fontRegular: 'Poppins-Regular',
  fontBold: 'Poppins-Bold',
  fontMedium: 'Poppins-Medium',
  semiBold: 'Poppins-SemiBold',
};
